### ISSUE TITLE
Issues with running goEagi on FreePBX

### ISSUE THREAD

**Issue by milutin-b** [andrewyang17/goEagi#3]
Hi,

I'm new to PBX and Go world and I'm trying to run your code on a FreePBX server once an extension is called so I could stream it to Google's Speech-To-Text API but with no luck.

Using the sample code you provided I crated an executable on FreePBX server, copied it to `/var/lib/asterisk/agi-bin` gave it permissions and wired it with an extension in `extensions_custom.conf` file like so:
```[from-internal]
exten => 100,1,Answer()
exten => 100,2,EAGI(goEagi)
exten => 100,2,DumpChan
```

Now when I call the extension in logs I get:
`res_agi.c: Launched AGI Script /var/lib/asterisk/agi-bin/goEagi`
`res_agi.c: <PJSIP/101-00000088>AGI Script goEagi completed, returning 0`

The script itself is executed (in it I'm creating a dummy file and writing to it) but it gets to `eagi, err := goEagi.New()` line where it simply stops executing. My understaning is that when run on my local machine it's waiting for agi variables through STDIN.

I tried writing a custom shell script which will pass arguments to STDIN but that didn't work either.

Is there anything I'm missing?
Thanks for your time.

**Comment by andrewyang17** [comment]
Hey Milutin,

Based on your description, I suspect it could be the permission issue, assuming you handled the errors gracefully in your script. Can you check the ownership and permissions of the directory/dummy file that you're writing to? 

For debugging purpose, you may write ```eagi, err := goEagi.New() ``` on top of the script first, and call its Verbose method to stdout any error to Asterisk CLI (remember to set "agi set debug on").

Let me know if it works, I will commit a better and latest sample code in README.md soon, probably this weekend.

**Comment by milutin-b** [comment]
Hi Andrew,

Thank you so much for taking the time to answer. 

Your debugging proposition led me in the right direction. It wasn't the files (I was only creating them just to make sure the program runs at all), but after Verbose-ing errors it was actually the google error stating it could not authenticate the json key.  Moved the file to directory accessible by asterisk, gave it permissions and it worked. The mix of program runing and then crashing with code 0 threw me for a loop.

Before you mark this as closed, could you share some tips on using your library for best results please?

Thank you again.

EDIT
To add to this comment, is there a way of using your solution to listen to actual calls in FreePBX? When I call an extension it never really reaches through to my softphone.

**Comment by andrewyang17** [comment]
Hey Milutin,

You're welcome! I'm glad you found the direction.

I'll come back to you again on tips using the library for better results after I released the latest version, basically to extend the flexibility of the APIs. You may fork the repo and make changes accordingly in places that fit to your requirements.

For softphone part, you have to write a program to set up a connection to AMI (Asterisk Manager Interface). With AMI, you'll be able to control the PBX, originate calls, check mailbox status, monitor channels and queues as well as execute Asterisk commands. In your case, one way of doing it is you create an event listener to listening a "DialEnd" event, and then execute "originate" actions to EAGI. In between, you would likely to go through a custom configuration file so that It won't simply originate any incoming call to EAGI. I give you an example:

Your program -> Connected to AMI (using any open source client library) -> Listening to "DialEnd" event -> check event does it calling to a specific extension that been configured in the configuration file -> if yes -> execute "originate" actions to EAGI

You have to define a context (example: "eagi-caller") in extensions_custom.conf file like so:

```
[eagi-caller]
exten => s,1,Answer
exten => s,n,EAGI(goEagi)
exten => s,n,Hangup
```

Then set the context and define the channel in your AMI action:
```
info, err := w.ami.Action(map[string]string{
  "Action":   "Originate",
  "Channel":  "LOCAL/s@chanspy",
  "Context":  "eagi-caller",
  "Exten":    "s",
  "Priority": "1"
})
```

So let's say you would like to get the transcription from both agent and caller, you have to execute "originate" action twice to EAGI contexts of "eagi-caller" and "eagi-agent", which means one call will execute two EAGI.

Here are some links for your reference (you may navigate the documentation to the Asterisk version that you're currently using):
1. https://wiki.asterisk.org/wiki/display/AST/Asterisk+16+ManagerEvent_DialEnd
2. https://wiki.asterisk.org/wiki/display/AST/Asterisk+16+ManagerAction_Originate
3. https://github.com/ivahaev/amigo
4. https://wiki.asterisk.org/wiki/display/AST/AMI+Libraries+and+Frameworks

**Comment by andrewyang17** [comment]
Hey Milutin,

You're welcome! I'm glad you found the direction.

I'll come back to you again on tips using the library for better results after I released the new version, it basically to extend the flexibility of the APIs. You may fork the repo and make changes accordingly in places that fit to your requirements.

For dialling to an extension into the softphone, this repo doesn't have the API for the setup. You may refer to this super awesome [playlist](https://www.youtube.com/watch?v=3UEBclNDDUE&list=PLnzEbgyK52Gu9fdVDHburrsG3KBIntXFK&index=5) for your experimentation.

**Comment by milutin-b** [comment]
Excellent - will check them out.

Thank you Andrew.
